name: Publish

on:
  push:
    tags: ["*"]

env:
  JAVA_MAJOR_VERSION: 21
  JAVA_JDK_VERSION: "21.0.5"
  MC_BASE_VERSION: "1.21"
  MC_COMPATIBLE_VERSION: "[1.21,1.22)"

jobs:
  build:
    if: github.repository == 'Hdoc1509/hotbar-keys'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_JDK_VERSION }}

      - name: Allow Gradlew Wrapper to be executed
        run: chmod +x ./gradlew

      # NOTE: tags have the format: {loader}-{mc-version}@{mod-version}
      #   i.e. fabric-1.21.x@0.1.0, neoforge-1.21.x@0.2.0
      - name: Setup Shareable Environment Variables
        run: |
          loader="$(cut --delimiter=- --fields=1 <<< "$TAG_NAME")"
          mod_version="$(cut --delimiter=@ --fields=2 <<< "$TAG_NAME")"
          changelog_body=$(./scripts/release-changelog-body.sh "$TAG_NAME" "$loader")
          printf '%s\n' "$GITHUB_ENV" \
            "CHANGELOG_BODY=$changelog_body" \
            "LOADER=$loader" \
            "LOADER_TITLE_CASE=${loader^}" \
            "JAR_FOLDER=$loader/build/libs" \
            "JAR_FILE_NAME=hotbar-keys-$loader-$MC_BASE_VERSION-$mod_version" \
            "MOD_VERSION=$mod_version" \
            "RELEASE_NAME=Hotbar Keys ($loader) $mod_version for Minecraft $MC_BASE_VERSION.x" \
            "TAG_NAME=$TAG_NAME"
        env:
          TAG_NAME: ${{ github.ref_name }}

      # NOTE: this allows to generate the correct version for .jar files
      - name: Update general `version` in gradle.properties
        run: |
          field="version"
          sed --in-place "s/^$field=.*/$field=$MOD_VERSION/" gradle.properties

      - name: Build Project
        run: ./gradlew "$LOADER:build"

      - name: Publish ${{ env.LOADER_TITLE_CASE }}
        if: ${{ success() }}
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 1169947
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: Lsq3tiTo
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-tag: ${{ env.TAG_NAME }}

          files: ${{ env.JAR_FOLDER }}/${{ env.JAR_FILE_NAME }}.jar

          name: ${{ env.RELEASE_NAME }}
          version: ${{ env.MOD_VERSION }}
          version-type: release
          changelog: ${{ env.CHANGELOG_BODY }}
          changelog-file: ${{ env.LOADER }}/CHANGELOG.md

          loaders: ${{ env.LOADER }}
          game-versions: ${{ env.MC_COMPATIBLE_VERSION }}
          java: ${{ env.JAVA_MAJOR_VERSION }}
